version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm run test
  deploy:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
            name: Deploy to Vercel
            command: npx vercel --name=todo-next --token=$VERCEL_TOKEN --prod --yes

workflows:
    version: 2.1
    ci-deploy:
      jobs:
        - build:
            name: build-and-test
        - deploy:
            requires: [build-and-test]
            filters:
              branches:
                only:
                  - develop