FROM node:18.16.1-alpine AS base

WORKDIR /app

COPY package*.json ./

RUN npm install --omit=dev

EXPOSE 3000 6006

FROM base AS development

RUN npm install

COPY . .

CMD ["npm", "run", "dev"]


FROM base AS production

COPY . .

RUN npm run build

CMD ["npm", "run", "start"]
